# Generated by Django 5.0.3 on 2024-06-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsoshistory',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='SOSHistory',
        ),
        migrations.DeleteModel(
            name='HistoricalSOSHistory',
        ),
    ]
