# Generated by Django 5.0.3 on 2024-06-24 16:09

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('securityCode', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('imageUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('groupId', api.models.CustomUUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('imageUrl', models.CharField(max_length=500)),
                ('users', models.ManyToManyField(related_name='user', to='api.usermodel')),
            ],
        ),
    ]
