# Generated by Django 5.0.3 on 2024-04-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_location_locationmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationModel',
            new_name='Location',
        ),
    ]
