# Generated by Django 5.0.3 on 2024-04-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_rename_location_locationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='securityCode',
            field=models.CharField(default=1, editable=False, max_length=500, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
