# Generated by Django 5.0.3 on 2024-04-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_locationmodel_securitycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='securityCode',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
