# Generated by Django 5.0.3 on 2024-06-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_historicallocationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLocationModel',
        ),
    ]
